name: Pages preview → Hostnet deploy (FTP clean)

on:
  push:
    branches: [ main ]      # pas aan als jouw default branch anders heet
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REMOTE_PATH: "/httpdocs/"  # Plesk/Hostnet documentroot (eindigend met /)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Maak een schone deploy-map zonder rommel
      - name: Prepare clean deploy folder (exclude junk)
        run: |
          mkdir -p deploy
          rsync -av \
            --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.gitignore' \
            --exclude='.gitattributes' \
            --exclude='README.md' \
            --exclude='LICENSE' \
            --exclude='INSTALL.txt' \
            --exclude='project.mobirise' \
            --exclude='publish-hashes.json' \
            --exclude='.vscode/' \
            --exclude='.idea/' \
            --exclude='node_modules/' \
            --exclude='**/*.psd' \
            --exclude='**/*.ai' \
            --exclude='**/*.kra' \
            --exclude='**/*.xcf' \
            --exclude='**/*.map' \
            ./ deploy/

      # Upload naar GitHub Pages (preview)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      # Bewaar dezelfde build voor FTP-deploy
      - name: Upload CI artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: deploy

  deploy_pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy_hostnet:
    needs: deploy_pages
    runs-on: ubuntu-latest
    environment: production     # zorg dat Environment 'production' bestaat met Required reviewers
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: site

      - name: FTP deploy to Hostnet
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SFTP_HOST }}      # hergebruik je bestaande secrets
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftp                         # evt. ftps als je host dat ondersteunt
          port: 21
          local-dir: site/                      # let op: trailing slash verplicht
          server-dir: ${{ env.REMOTE_PATH }}    # let op: trailing slash verplicht
          exclude: |                            # extra zekerheid naast de 'clean' stap
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
            README.md
            LICENSE
            INSTALL.txt
